# Generated by Django 3.2.14 on 2022-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220803_1203'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('id', 'name', 'measurement_unit'), name='unique ingredient'),
        ),
    ]
